#!/bin/sh
while [ $# -gt 0 ]; do
echo "T $1"  # T to prevent switch interpretations  :(
psql >/dev/null 2>&1 <<EOF
drop schema if exists yddb_test_test_test cascade;
create schema yddb_test_test_test;
EOF
psql -Aqt -v "script=$1" <<EOF 2>&1 |sed "s,^psql:$1:[0-9]*:,psql::," |diff -u "${1%%.sql}.expected" -
set search_path=yddb_test_test_test;
\i $1
EOF
shift
done
